### ISSUE TITLE
Archive Package on CRAN

### ISSUE THREAD

**Issue by kylehamilton** [ropensci/RCryptsy#10]
Hey @sckott I'm going to archive the package tomorrow because the site has been taken down and is now in receivership.

http://www.cryptsysettlement.com/
http://cryptsyreceivership.com/
http://www.coindesk.com/cryptsy-ceo-millions-digital-currency-steal/

**Comment by sckott** [comment]
Okay, thanks for letting me know

**Comment by sckott** [comment]
@kylehamilton did you ask CRAN to archive this yet? it still appears to be up on CRAN

**Comment by sckott** [comment]
@kylehamilton ^^

**Comment by sckott** [comment]
@kylehamilton any thoughts on when you will be able to do this, please do it as soon as possible

**Comment by kylehamilton** [comment]
Sorry for the delay, I thought I had sent the email to CRAN but it was in my drafts folder. Sent the email today and according to Uwe the package has been archived.

**Comment by sckott** [comment]
great, thanks!
