### ISSUE TITLE
Tags and releases

### ISSUE THREAD

**Issue by sckott** [ropensci/RCryptsy#8]
hi @kylehamilton - could you use tags and releases?  Looks like you've used tags before and releases before https://github.com/ropensci/RCryptsy/releases/tag/1.0  So if you could make sure to tag any cran releases, and put in the releases github page the relavant news bits for that tag?

**Comment by kylehamilton** [comment]
Sorry about that, I kept getting updates about the build failing and got a little tunnel vision trying to get the changes added. Added the changes to the new release info and the correct version number.
